In [1]:
import numpy as np

In [4]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.array([0,0,0,0,0])

array([0, 0, 0, 0, 0])

In [5]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.full((3,4),3.1416)

array([[3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416]])

In [11]:
# create aan array of 5 values evenly spaced between  0 and 2

np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
#arrange function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [27]:
#create an array of random integer
np.random.seed(13)
print(np.random.randint(50,100,10))
np.random.randint(50,100,(5,3))

[68 98 60 66 88 84 75 94 85 76]


array([[52, 96, 87],
       [63, 60, 59],
       [61, 52, 82],
       [69, 71, 69],
       [61, 72, 61]])

In [28]:
#create an array filled values between 0 and 1

np.random.random((4,3))

array([[0.25627995, 0.34758122, 0.00941277],
       [0.35833378, 0.94909418, 0.21789901],
       [0.31939137, 0.91777239, 0.03190367],
       [0.06508454, 0.629829  , 0.87381344]])

In [35]:
## return a sample(or sample) from standard normal distribution

np.random.randn(5,3)

array([[ 0.45348104,  0.92234415, -0.2073497 ],
       [-0.37591996,  0.63988397,  2.05369324],
       [-0.92833523, -0.77466003, -0.43714566],
       [ 0.54791831, -0.85414295,  0.46565797],
       [-0.72099967,  0.56226171, -0.31485808]])

In [42]:
##draw random samples from a gaussian normal distribution
np.random.seed(56)
a=np.random.normal(0,1,(5,3))

In [43]:
a.dtype

dtype('float64')

In [44]:
a

array([[-1.03764318,  0.59365816,  1.10268062],
       [-0.51217773, -0.26541986, -1.61700601],
       [-0.27151449,  0.94555425, -0.62699279],
       [-0.26594728,  0.68729358,  2.04845691],
       [-0.46155895,  0.68784742,  1.00812262]])

In [45]:
np.transpose(a)

array([[-1.03764318, -0.51217773, -0.27151449, -0.26594728, -0.46155895],
       [ 0.59365816, -0.26541986,  0.94555425,  0.68729358,  0.68784742],
       [ 1.10268062, -1.61700601, -0.62699279,  2.04845691,  1.00812262]])

In [46]:
a.T

array([[-1.03764318, -0.51217773, -0.27151449, -0.26594728, -0.46155895],
       [ 0.59365816, -0.26541986,  0.94555425,  0.68729358,  0.68784742],
       [ 1.10268062, -1.61700601, -0.62699279,  2.04845691,  1.00812262]])